name: mnemonic
description: A Dart package to generate and recover mnemonic phrases and lightning seeds for unified Bitcoin and Lightning wallets.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  ffigen: ^8.0.2

dependencies:
  ffi: ^2.0.2
  hex: ^0.2.0
  path: ^1.8.3
  path_provider: ^2.0.15

ffigen:
  name: mnemonic_ffi
  description: A Dart bindings for the Rust library to generate and derive seeds.
  output: lib/src/mnemonic_ffi.dart
  headers:
    entry-points:
      - rust/libmnemonic_ffi.h
  compiler-opts: "-Wno-nullability-completeness"
